# Generated by Django 5.1.6 on 2025-02-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_en', models.TextField()),
                ('answer_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='təlimlər',
            name='bootcamp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamptipi', to='main.bootcamptipi'),
        ),
        migrations.AlterModelTable(
            name='bootcamps',
            table='main_bootcamps',
        ),
    ]
