# Generated by Django 5.1.6 on 2025-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_broadcasts_script_sessions_script_syllabus_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
