# Generated by Django 5.1.6 on 2025-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_scripts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
