# Generated by Django 5.1.6 on 2025-02-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bootcamptipi_bootcamp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamptipi',
            name='bootcamp_type',
        ),
        migrations.AddField(
            model_name='bootcamptipi',
            name='bootcamp',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_tipi', to='main.bootcamps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mətinlər',
            name='trainings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metinler', to='main.təlimlər'),
        ),
        migrations.AlterField(
            model_name='nümayişlər',
            name='metinler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nümayislər', to='main.mətinlər'),
        ),
        migrations.AlterField(
            model_name='təlimlər',
            name='bootcamp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telimler', to='main.bootcamptipi'),
        ),
    ]
