# Generated by Django 5.1.6 on 2025-02-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bootcamptipi_bootcamp_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamptipi',
            name='bootcamp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_tipi', to='main.bootcamps'),
        ),
    ]
